[package]
name = "use-return"
version = "0.2.0"
publish = true
keywords = ["quant", "return", "log", "simple", "rustuse"]
description = "Primitive quantitative return vocabulary for RustUse"
homepage = "https://rustuse.org/use-quant/use-return"
documentation = "https://docs.rs/use-return"
readme = "README.md"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
